apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: keycloaks.aerogear.org
spec:
  group: aerogear.org
  names:
    kind: Keycloak
    listKind: KeycloakList
    plural: keycloaks
    singular: keycloak
  scope: Namespaced
  version: v1alpha1
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            version:
              type: string
            instanceID:
              type: string
            adminCredentials:
              type: string
            realms:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                  authTypes:
                    type: array
                    items:
                      type: object
                      properties:
                        provider:
                          type: string
                        clientID:
                          type: string
                        outputSecret:
                          type: string
                  users:
                    type: array
                    items:
                      type: object
                      properties:
                        username:
                          type: string
                        outputSecret:
                          type: string
                        roles:
                          type: array
                          items:
                            type: string
                  clients:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        clientType:
                          type: string
                        config:
                          type: object
                        outputSecret:
                          type: string