apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: keycloaks.aerogear.org
spec:
  group: aerogear.org
  names:
    kind: Keycloak
    listKind: KeycloakList
    plural: keycloaks
    singular: keycloak
  scope: Namespaced
  version: v1alpha1
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            version:
              type: string
            instanceID:
              type: string
            adminCredentials:
              type: string
            realms:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
                  realm:
                    type: string
                  enabled:
                    type: boolean
                  displayName:
                    type: string
                  identityProviders:
                    type: array
                    items:
                      type: object
                      properties:
                        alias:
                          type: string
                        displayName:
                          type: string
                        internalId:
                          type: string
                        providerId:
                          type: string
                        enabled:
                          type: boolean
                        trustEmail:
                          type: boolean
                        storeToken:
                          type: boolean
                        addReadTokenRoleOnCreate:
                          type: boolean
                        firstBrokerLoginFlowAlias:
                          type: string
                        postBrokerLoginFlowAlias:
                          type: string
                        config:
                          type: object
                  users:
                    type: array
                    items:
                      type: object
                      properties:
                        username:
                          type: string
                        firstName:
                          type: string
                        lastName:
                          type: string
                        email:
                          type: string
                        emailVerified:
                          type: boolean
                        enabled:
                          type: boolean
                        realmRoles:
                          type: array
                          items:
                            type: string
                        clientRoles:
                          type: object
                        requiredActions:
                          type: array
                          items:
                            type: string
                        groups:
                          type: array
                          items:
                            type: string
                  clients:
                    type: object
                    # items:
                    #   type: object
                    #   properties:
                    #     name:
                    #       type: string
                    #     clientType:
                    #       type: string
                    #     config:
                    #       type: object
                    #     outputSecret:
                    #       type: string